[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "vite"
  targetPort = 3000
  port = 8888

[[edge_functions]]
  path = "/api/sendWhatsAppMessage"
  function = "sendWhatsAppMessage"