[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "#auto"
  targetPort = 5173
  port = 8888
  functionsPort = 9999

[[edge_functions]]
  path = "/api/sendWhatsAppMessage"
  function = "sendWhatsAppMessage"